export default [
    { label: '恐怖', value: '恐怖' },
    { label: '悬疑', value: '悬疑' },
    { label: '有剧情', value: '有剧情' },
    { label: '古风', value: '古风' },
    { label: '微恐', value: '微恐' },
    { label: '角色扮演', value: '角色扮演' },
    { label: '单人任务', value: '单人任务' },
    { label: '非恐', value: '非恐' },
    { label: '重恐', value: '重恐' },
    { label: '科幻', value: '科幻' },
    { label: '中恐', value: '中恐' },
    { label: '新手', value: '新手' },
    { label: '对抗', value: '对抗' },
    { label: '高玩', value: '高玩' },
    { label: '多种支线', value: '多种支线' },
    { label: '真人NPC', value: '真人NPC' },
    { label: '机械', value: '机械' },
    { label: '运动量大', value: '运动量大' },
    { label: '小朋友可玩', value: '小朋友可玩' },
    { label: '二次元', value: '二次元' },
    { label: '大型机械', value: '大型机械' },
    { label: 'VR', value: 'VR' },
]